### ISSUE TITLE
Explain how to get figma tokens

### ISSUE THREAD

**Issue by ikbendewilliam** [ikbendewilliam/flutter_figma_theme_generator#5]

**Comment by fruts** [comment]
please explain how can i generate figma tokens for this lib?

**Comment by ikbendewilliam** [comment]
Hi @fruts, I don't think it will work. The whole setup from figma changed and I will need to reevaluate if this is possible. 
We used a plugin to retrieve tokens, I don't know which one, I could find out but then you will also need a specific structure in your figma setup. 
Sorry to disappoint you
